apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels: 
    app: {{ .Values.deployment.labels }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels }}
    spec:
#      volumes:
#      - name: app-api-volume
#        persistentVolumeClaim:
#          claimName: beezz-pvc
      containers:
        - name: myapp
          image: {{ .Values.deployment.image.app }}
          ports:
          - containerPort: 3000
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
#          volumeMounts:
#            - name: app-api-volume
#              mountPath: /apps/app-api-volume
