apiVersion: v1
kind: Secret
metadata:  
  name: {{ .Values.secrets.name }}
type: Opaque
data:  
  mongo-root-username: {{ .Values.secrets.data.username }}
  mongo-root-password: {{ .Values.secrets.data.password }}