apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beezz-pvc
  namespace: beezz-ns
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
