apiVersion: apps/v1
kind: Deployment
metadata:
  name: petapp-api
  namespace: beezzy-app
  labels: 
    app: petapp-api
spec:
  selector:
    matchLabels:
      app: beezz-app
  replicas: 1
  template:
    metadata:
      labels:
        app: beezz-app
    spec:
      volumes:
      - name: app-api-volume
        persistentVolumeClaim:
          claimName: beezz-pvc
      containers:
        - name: myapp
          image: beezzbank/gradecal:3.0
          resources:
            limits:
              cpu: 10m
              memory: 80Mi
            requests:
              cpu: 10m
              memory: 80Mi
          volumeMounts:
            - name: app-api-volume
              mountPath: /apps/app-api-volume
