name: Lab-workflow
on:
  push:
    branches:
      - main
env:
  WORDING: "beezz"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check github environment
        run: hostname

      - name: create variable
        run: echo "BUILD_ARGS=prod-1.0.0" >> $GITHUB_ENV
      
      - name: build-app
        run: echo "build for ${{ env.WORDING }} by $BUILD_ARGS "

  deploy:
    runs-on: self-hosted
    steps:
      - name: check github environment
        run: hostname
