name: new-deploy
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
   inputs:
     version:
       description: 'input version'
       default: '1.1'
       required: true
env:
  NAMESPACE: beezz-ns
jobs:
  tag:
    runs-on: self-hosted
    steps:
      - name: Set Tag on Workflow Dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "${{ github.event.inputs.version }}"
  build:
    needs: tag
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: docker login
        run: docker login -u beezzbank -p ${{ Secrets.DOCKER_PASS }}

      - name: build and push 
        run: |
          cd Docker
          docker build -t beezzbank/register-app:${{ github.event.inputs.version }} .
          docker push beezzbank/register-app:${{ github.event.inputs.version }}

  Deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: wait for Approve    
        uses: trstringer/manual-approval@v1
        id: check-approval
        with:
          secret: ${{ github.TOKEN }}
          approvers: "Beezzbank"
          minimum-approvals: 1
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
      - name: create deploy
        run: |
          pwd
           
 
