name: new-deploy
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
   inputs:
     version:
       description: 'input version'
       default: '1.1'
       required: true
env:
  NAMESPACE: beezz-ns
jobs:
  tag:
    runs-on: self-hosted
    steps:
      - name: Set Tag on Workflow Dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "${{ github.event.inputs.version }}"
  build:
    needs: tag
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: docker login
        run: docker login -u beezzbank -p ${{ Secrets.DOCKER_PASS }}

      - name: build and push 
        run: |
          cd Docker
          docker build -t beezzbank/register-app:${{ github.event.inputs.version }} .
          docker push beezzbank/register-app:${{ github.event.inputs.version }}

  Deploy:
    needs: build
    runs-on: self-hosted
    environment:
      name: dev
    steps:
      - name: Call Share Action from another repository
        uses: corp-ais/cbvs-utils/.github/actions@v1 
        with:
          HOST_IP: ${{ vars.HOST_IP }}
      - name: Minikube start
        run:
          minikube start

      - name: create deploy
        run: |
          kubectl apply -f ./Kube/beezz-ing.yaml
          kubectl apply -f ./Kube/beezz-svc.yaml
          kubectl apply -f ./Kube/beezz-deploy.yaml
