name: example-flow
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: docker login
        run: docker login -u beezzbank -p ${{ Secrets.DOCKER_PASS }}

      - name: build and push 
        run: |
          cd Docker
          docker build -t beezzbank/register-app:1.1 .
          docker push beezzbank/register-app:1.1
  Deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: helm-upgrade
        run: helm upgrade -i register-helm -f Helm/values.yaml Helm
 
